Add GUI notification mode for Desktop usage

diff --git a/check_lvm_ThinPool b/check_lvm_ThinPool
--- a/check_lvm_ThinPool
+++ b/check_lvm_ThinPool
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 # VERSION 1.2 - 2018-01-25
+# VERSION 1.3 - 2018-05-10 - Add Gui Notify
 #
 # check_lvm_ThinPool - check usage of lvm ThinPool
 #
@@ -43,6 +44,7 @@
 # 13 (check_int)    $1 opts: $2 is not a number
 # 14 (check_int)    $1 opts: $2 need interval between 0-100
 # 16                binary not known
+# 17                Performance data is not compatible with GUI notification mode
 
 ################################################################################
 ##########                        DEFAULTS OPTIONS                    ##########
@@ -50,6 +52,7 @@
 WARNING=80
 CRITICAL=90
 PERF_DATA=false
+GUI_NOTIFY=false
 
 ################################################################################
 
@@ -75,6 +78,7 @@ function usage()
     echo "    -w, --warning  <percent>    Define usage warning percent (between 0-100, default: 80)"
     echo "    -c, --critical <percent>    Define usage critical percent (between 0-100, default: 100)"
     echo "    -p, --perf-data             Enable performance data output"
+    echo "    -g, --gui-notify <user>     Enable GUI notification mode for Desktop usage"
     echo "    -e, --examples              Show usage examples"
     echo "    -h, --help                  Print this help"
     echo ""
@@ -91,15 +95,23 @@ function examples()
     yellow="$(tput setaf 3)"
     green="$(tput setaf 2)"
     reset="$(tput sgr0)"
-    echo "${yellow}Usage examples:${reset}"
     echo ""
-    echo "${green}Simple check${reset}"
+    echo "${yellow}                          ** Usage examples **${reset}"
+    echo ""
+    echo "${green}Simple check:${reset}"
     echo "${yellow}check_lvm_ThinPool vg_srv-1 LXDThinpool${reset}"
     echo "    OK - ThinPool vg_srv-1/LXDThinpool: data=63,40% snap=63,40% meta=32,76%"
     echo ""
     echo "${green}Change range Waning and Critical:${reset}"
     echo "${yellow}check_lvm_ThinPool -w 50 -c 60 vg_srv-1 LXDThinpool${reset}"
     echo "    CRITICAL - ThinPool vg_srv-1/LXDThinpool: data=63,41% snap=63,41% meta=32,76%"
+    echo ""
+    echo "${green}Desktop usage (GUI notification):${reset}"
+    echo "${yellow}check_lvm_ThinPool --gui-notify alban vg_port lv_ThinPool${reset}"
+    echo "    (No CLI output, just in notification area)"
+    echo "    LVM ThinPool Alert"
+    echo "    ThinPool vg_port/lv_ThinPool data=61,03% snap=61,03% meta=20,11%"
+    echo "    "
     echo ""
 
     exit 0
@@ -164,6 +176,13 @@ do
         "-p"|"--perf-data")
             PERF_DATA=true # Enable performance data output
             ;;
+        "-g"|"--gui-notify")
+            # Check if notify-send binary is available
+            check_binary notify-send libnotify-bin
+            GUI_USER=$2
+            GUI_NOTIFY=true
+            shift
+            ;;
         *)
             error 4 Unknown option: $1
             ;;
@@ -172,6 +191,11 @@ do
     shift
     opt="$1"
 done
+
+# TEST if PERF_DATA=true AND GUI_NOTIFY=true
+if $PERF_DATA && $GUI_NOTIFY ; then
+    error 17 "Performance data is not compatible with GUI notification mode"
+fi
 
 # TEST if WARN > to CRIT => ERR
 if [ $WARNING -ge $CRITICAL ] ;then
@@ -270,10 +294,22 @@ else                               # OK
     exit_code=0
 fi
 
-# Print output :
-echo "$output_prefix $output"
-if $PERF_DATA ; then
-    echo " | ${vg_name}/${lv_name}_data=${data_percent}% ${vg_name}/${lv_name}_snap=${snap_percent}% ${vg_name}/${lv_name}_meta=${metadata_percent}%"
+if ! $GUI_NOTIFY ; then
+    # CLI mode (nagios, icinga....)
+    # Print output :
+    echo "$output_prefix $output"
+    if $PERF_DATA ; then
+        echo " | ${vg_name}/${lv_name}_data=${data_percent}% ${vg_name}/${lv_name}_snap=${snap_percent}% ${vg_name}/${lv_name}_meta=${metadata_percent}%"
+    fi
+else
+    # GUI mode
+    # Notify only if return code is not 0
+    if [ $exit_code -ne 0 ] ; then
+        export HOME="/home/$GUI_USER"
+        export DISPLAY=:0.0
+        EXPIRE_TIME=60000 # 60 seconds
+        notify-send --icon=drive-multidisk --urgency=critical --expire-time=$EXPIRE_TIME "LVM ThinPool Alert" "$output_prefix $output"
+    fi
 fi
 
 exit $exit_code
